# Generated by Django 5.2.4 on 2025-07-30 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auctions_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='bidPrice',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to='auctions.auctions')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchLists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
